"use client";

import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAppSelector } from "@/hooks/useAppStore";
import { selectIsAdmin } from "@/store/slices/authSlice";
import { reportService } from "@/services/api";
import { formatDateTime } from "@/lib/formatters";
import { toast } from "sonner";
import { FileText, Plus, Trash2, Download } from "lucide-react";
import type { PageResponse, ReportResponse } from "@/types";
import { Skeleton } from "@/components/ui/skeleton";

export default function ReportsPage() {
  const isAdmin = useAppSelector(selectIsAdmin);
  const [reports, setReports] = useState<ReportResponse[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [page, setPage] = useState(0);
  const [totalPages, setTotalPages] = useState(0);

  const [newTitle, setNewTitle] = useState("");
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");

  const fetchReports = async () => {
    setIsLoading(true);
    try {
      const res = await reportService.getAll(page, 10);
      const data = res.data as PageResponse<ReportResponse>;
      setReports(data.content);
      setTotalPages(data.totalPages);
    } catch {
      toast.error("Failed to fetch reports");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, [page]);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle || !fromDate || !toDate) {
      toast.error("Please fill all fields");
      return;
    }
    try {
      await reportService.create({ title: newTitle, fromDate, toDate });
      toast.success("Report generated successfully");
      setNewTitle("");
      setFromDate("");
      setToDate("");
      fetchReports(); // Refresh
    } catch {
      toast.error("Failed to generate report");
    }
  };

  const handleDelete = async (id: number) => {
    if (!confirm("Delete this report?")) return;
    try {
      await reportService.delete(id);
      toast.success("Report deleted");
      fetchReports();
    } catch {
      toast.error("Failed to delete report");
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold tracking-tight">System Reports</h1>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {isAdmin && (
          <Card className="lg:col-span-1">
            <CardHeader>
              <CardTitle>Generate New Report</CardTitle>
              <CardDescription>Create a PDF summary report</CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleGenerate} className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="title">Report Title</Label>
                  <Input 
                    id="title" 
                    value={newTitle} 
                    onChange={(e) => setNewTitle(e.target.value)} 
                    placeholder="e.g., Weekly Summary" 
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="fromDate">From Date</Label>
                  <Input 
                    id="fromDate" 
                    type="date" 
                    value={fromDate} 
                    onChange={(e) => setFromDate(e.target.value)} 
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="toDate">To Date</Label>
                  <Input 
                    id="toDate" 
                    type="date" 
                    value={toDate} 
                    onChange={(e) => setToDate(e.target.value)} 
                  />
                </div>
                <Button type="submit" className="w-full">
                  <Plus className="mr-2 h-4 w-4" /> Generate Report
                </Button>
              </form>
            </CardContent>
          </Card>
        )}

        <Card className={isAdmin ? "lg:col-span-2" : "col-span-1 lg:col-span-3"}>
          <CardHeader>
            <CardTitle>Report History</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="rounded-md border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Title</TableHead>
                    <TableHead>Period</TableHead>
                    <TableHead>Generated By</TableHead>
                    <TableHead>Date</TableHead>
                    <TableHead className="w-[100px]"></TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {isLoading ? (
                    Array.from({ length: 5 }).map((_, i) => (
                      <TableRow key={i}>
                        <TableCell><Skeleton className="h-4 w-32" /></TableCell>
                        <TableCell><Skeleton className="h-4 w-24" /></TableCell>
                        <TableCell><Skeleton className="h-4 w-16" /></TableCell>
                        <TableCell><Skeleton className="h-4 w-24" /></TableCell>
                        <TableCell><Skeleton className="h-8 w-16" /></TableCell>
                      </TableRow>
                    ))
                  ) : reports.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={5} className="h-24 text-center text-muted-foreground">
                        No reports generated yet.
                      </TableCell>
                    </TableRow>
                  ) : (
                    reports.map((report) => (
                      <TableRow key={report.id}>
                        <TableCell className="font-medium flex items-center gap-2">
                          <FileText className="h-4 w-4 text-primary" />
                          {report.title}
                        </TableCell>
                        <TableCell className="text-sm">
                          {report.fromDate} to {report.toDate}
                        </TableCell>
                        <TableCell>{report.generatedBy}</TableCell>
                        <TableCell className="whitespace-nowrap">
                          {formatDateTime(report.generatedAt)}
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            <Button variant="ghost" size="icon" title="Download API Data (JSON)">
                              <Download className="h-4 w-4 text-emerald-500" />
                            </Button>
                            {isAdmin && (
                              <Button variant="ghost" size="icon" onClick={() => handleDelete(report.id)}>
                                <Trash2 className="h-4 w-4 text-destructive" />
                              </Button>
                            )}
                          </div>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </div>
            <div className="flex items-center justify-between space-x-2 pt-4">
              <div className="text-sm text-muted-foreground">
                Page {page + 1} of {totalPages || 1}
              </div>
              <div className="flex items-center space-x-2">
                <Button variant="outline" size="sm" onClick={() => setPage(page - 1)} disabled={page === 0}>
                  Prev
                </Button>
                <Button variant="outline" size="sm" onClick={() => setPage(page + 1)} disabled={page >= totalPages - 1}>
                  Next
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
